name: CI
on: [ push, pull_request ]
jobs:
  golangci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: '1.20'

      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Run Check
        run: |
          echo "ls ./"
          ls
          rm -rf Wife/*.go Wife/*.md Wife/.git
          echo "ls Wife/"
          ls Wife/
          go mod init updater
          sed -i '1,3d' main.go
          go mod tidy
          go run main.go -c
